### ISSUE TITLE
安装包配置中未包括static目录及目录下的index.html文件

### ISSUE THREAD

**Issue by foxgoblin** [vnpy/vnpy_webtrader#12]
安装包配置中未包括static目录及目录下的index.html文件。因此启动 webserver 后无法访问对应页面。服务端报错：
`  File "/usr/local/lib/python3.7/site-packages/vnpy_webtrader/web.py", line 141, in index
    with open(index_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/vnpy_webtrader/static/index.html'`

**Comment by Edanflame** [comment]
缺少应该是pypi打包的问题，可以从github源码中复制static目录至缺少的位置

**Comment by vnpy** [comment]
已修复
