### ISSUE TITLE
vnpy2.9 Ubuntu18下no ui启动问题

### ISSUE THREAD

**Issue by tengchitim** [vnpy/vnpy_webtrader#16]
vnpy2.9版本下， 尝试no ui 启动vnpy_webtrader
参照GitHub 上被remove的代码启动
https://github.com/vnpy/vnpy_webtrader/blob/306c3c7e42315cb82be567db65a8d700e1710282/script/no_ui.py

发现触发币安send_order时候环境和启动时候环境不一致，send_order时候部分变量没有被初始化，导致接口调用失败

![微信图片_20220209191118](https://user-images.githubusercontent.com/10702392/153348552-c821e280-6a09-44eb-b888-887a944f65e0.png)
/docs的界面能正常打开，访问账号余额也能正常访问，就是发送订单发送不了
本地win10 的ui版本是能正常下单的

**Comment by Edanflame** [comment]
测试使用ctp接口是可以正常下单，推荐使用ui脚本启动
