### ISSUE TITLE
子进程无法及时退出

### ISSUE THREAD

**Issue by Edanflame** [vnpy/vnpy_webtrader#6]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.4.0
* vn.py版本: v2.4.0发行版

## Issue类型
三选一：Bug

## 预期程序行为
使用ctrl+C后整个程序全部关闭

## 实际程序行为
使用ctrl+C后，主进程关闭，子进程中的rpcClient继续运行，导致子进程无法关闭，并在30秒后打印: 
```python
RpcServer has no response over 30.0 seconds, please check you connection.
```
然后子进程才会退出

**Comment by vnpy** [comment]
正常关闭图形界面后，整个程序会正常退出。
